server:
  #application:
  #  name: user-service
  port: 3333 #443
  forward-headers-strategy: FRAMEWORK
# register service registry (discovery server)
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password@localhost:1111/eureka
    healthcheck:
      enabled: false
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
spring:
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
  show-sql: true
  h2:
  console:
    enabled: true

jwt:
  header: Authorization
  secret: 3ef572f7769d78d
  expiration: 7200

soapWebservice:
  user: Admin
  password: pa$$w0rd

allow:
  origin: localhost
